v## Site info:
title: "I CAN'T BLEND"
tagline: "Yes, You Can!"
author: Hasan Basri Kenar
email: fidensart@gmail.com
description: "Blender" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Blender"
baseurl: "/icantblend" # the subpath of your site, e.g. /blog
url: "http://icantblend.com" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
github_username: c6parmak
favicon: "{{ site.baseurl }}/images/favicon.ico"
aboutme: Hi, this is Hasan Basri Kenar. # these are shown on aboutme-sidebar.
aboutme_photo: "/images/hasan.jpg" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

#excerpt_separator: <!--more-->

locales:
  en:
    Aboutme: "About Me"
    Archives: "Archives"
    Categories: "Categories"
    Recent_Posts: "Recent Posts"
    Tags: "Tags"
    Previous: "Older"
    Next: "Newer"
    PostedInCategories: "Posted in"
    Taggedwith: "and tagged"
    PostDate: "on "

### Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
highlighter: pygments
paginate: 10
